# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html

fos_rest:
    body_converter:
        enabled: true # automatic deserialization of request's content
        validate: true
        validation_errors_argument: validationErrors

    format_listener:
        enabled: true
        rules:
            - { path: '^/articles', priorities: ['json', 'xml'], fallback_format: 'json' }

    view:
        view_response_listener: true
        formats: { json: true, xml: true }

    serializer:
        serialize_null: true # do not ignore null values

    exception:
        enabled: true

    param_fetcher_listener: true